# Домашнее задание №1

In [283]:
#  №0. pip install torch torchvision
import torch

In [284]:
#  №1. Создайте случайный FloatTensor размера 3x4x5
# 3x4x5 -- [T0,T1,T2], где Ti -- тензор размера 4х5, i in {0,1,2}

#задание вручную
x = torch.FloatTensor([[[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]], 
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]],
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]]])

#задание случайными числами
y = torch.randn(3, 4, 5)

x, y

(tensor([[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]]]),
 tensor([[[-1.1296e+00, -3.3618e-01,  4.1756e-01,  2.0322e-01, -6.7322e-01],
          [-5.2487e-01,  7.6582e-01, -6.7262e-01, -1.3538e+00, -8.7185e-01],
          [ 5.7152e-01,  7.8056e-01,  1.5534e-03,  1.8716e+00, -9.8426e-01],
          [ 1.9177e+00,  1.2524e+00,  6.7699e-02, -1.8298e+00,  9.5581e-01]],
 
         [[ 3.3777e-01, -1.2843e-02,  1.8645e+00, -2.0056e+00, -1.8494e-01],
          [-5.9428e-01, -6.9271e-01,  3.4932e-01, -1.0565e+00,  2.0672e+00],
          [-8.0803e-01, -1.1842e+00, -2.0218e+00, -1.3432e+00,  6.3282e-01],
          [ 7.7571e-01,  9.4250e-01, -1.1210e+00,  1.2559e+00, -6

In [285]:
# №2.Выведите его форму (shape)
print('Тензор x: ', x.type(), x.shape)
print('Тензор y: ', y.type(), y.shape)

Тензор x:  torch.FloatTensor torch.Size([3, 4, 5])
Тензор y:  torch.FloatTensor torch.Size([3, 4, 5])


In [286]:
# №3.Приведите его к форме 6 X 10
x = torch.reshape(x, [6, 10])
x, x.shape

(tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.]]),
 torch.Size([6, 10]))

In [287]:
# № 4. Создайте случайный IntTensor размера 10

a = torch.IntTensor(10)
a.type(), a

('torch.IntTensor', tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=torch.int32))

In [288]:
# № 5. Умножьте созданный FloatTensor на созданный IntTensor поэлементно
x * a

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [289]:
# №6. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x @ x.T

tensor([[ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.]])

In [290]:
# №7. Посчитайте производную функции y = x**3 + z - 75*t в точке (1, 0.5, 2)

x = Variable(torch.Tensor([1]), requires_grad = True) #переменная является обучаемой
z = Variable(torch.Tensor([0.5]), requires_grad = True) #переменная является обучаемой
t = Variable(torch.Tensor([2]), requires_grad = True) #переменная является обучаемой

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() #считаем производную по всем переменным

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) #частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [291]:
# №8. Создайте единичный тензор размера 5x6
e = torch.ones([5, 6])
e, e.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]))

In [292]:
# №9. Переведите его в формат numpy
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)