# Домашнее задание №1

In [250]:
#  №0. pip install torch torchvision
import torch

In [251]:
#  №1. Создайте случайный FloatTensor размера 3x4x5
# 3x4x5 -- [T0,T1,T2], где Ti -- тензор размера 4х5, i in {0,1,2}

#задание вручную
x = torch.FloatTensor([[[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]], 
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]],
                       
                       [[1,1,1,1,1], 
                        [2,2,2,2,2], 
                        [3,3,3,3,3], 
                        [4,4,4,4,4]]])

#задание случайными числами
y = torch.randn(3, 4, 5)

x, y

(tensor([[[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]],
 
         [[1., 1., 1., 1., 1.],
          [2., 2., 2., 2., 2.],
          [3., 3., 3., 3., 3.],
          [4., 4., 4., 4., 4.]]]),
 tensor([[[-1.7181,  0.7462,  0.0174, -2.6310,  0.8026],
          [ 0.8942, -1.0792, -1.5135,  0.3535,  0.0228],
          [ 1.1378, -0.1720,  0.3407, -0.8262, -0.6021],
          [ 0.5701, -0.0956,  1.3401, -0.5834, -0.9137]],
 
         [[ 0.5801, -1.1524,  1.1603, -0.4561, -0.5784],
          [-0.5211,  1.1087, -1.2720, -0.8053,  1.1849],
          [-0.6044, -1.5999,  0.4108, -1.0160, -0.5624],
          [ 1.1808, -0.5094, -0.4535,  0.1717,  0.9704]],
 
         [[ 1.2289, -0.9833,  0.8134, -0.0929, -0.5941],
          [-0.2322,  0.3079, -1.4246,  0.6403, -1.1102],
          [ 0.3906,  2.7973,  0

In [252]:
# №2.Выведите его форму (shape)
print('Тензор x: ', x.type(), x.shape)
print('Тензор y: ', y.type(), y.shape)

Тензор x:  torch.FloatTensor torch.Size([3, 4, 5])
Тензор y:  torch.FloatTensor torch.Size([3, 4, 5])


In [253]:
# №3.Приведите его к форме 6 X 10
x_r = torch.reshape(x, [6, 10])
x_r, x_r.shape

(tensor([[1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.],
         [1., 1., 1., 1., 1., 2., 2., 2., 2., 2.],
         [3., 3., 3., 3., 3., 4., 4., 4., 4., 4.]]),
 torch.Size([6, 10]))

In [254]:
# №4. Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
import numpy as np

# тензор до изменения формы
a = torch.tensor([1, 4, 2, 2, 1])
x * a

tensor([[[ 1.,  4.,  2.,  2.,  1.],
         [ 2.,  8.,  4.,  4.,  2.],
         [ 3., 12.,  6.,  6.,  3.],
         [ 4., 16.,  8.,  8.,  4.]],

        [[ 1.,  4.,  2.,  2.,  1.],
         [ 2.,  8.,  4.,  4.,  2.],
         [ 3., 12.,  6.,  6.,  3.],
         [ 4., 16.,  8.,  8.,  4.]],

        [[ 1.,  4.,  2.,  2.,  1.],
         [ 2.,  8.,  4.,  4.,  2.],
         [ 3., 12.,  6.,  6.,  3.],
         [ 4., 16.,  8.,  8.,  4.]]])

In [255]:
# тензор после изменения формы
a_r = a.repeat(1,2)
x_r * a_r

tensor([[ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.],
        [ 1.,  4.,  2.,  2.,  1.,  2.,  8.,  4.,  4.,  2.],
        [ 3., 12.,  6.,  6.,  3.,  4., 16.,  8.,  8.,  4.]])

In [256]:
# №5. Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
x_r @ x_r.T

tensor([[ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.],
        [ 25.,  55.,  25.,  55.,  25.,  55.],
        [ 55., 125.,  55., 125.,  55., 125.]])

In [257]:
# №6. Посчитайте производную функции y = x**3 + z - 75*t в точке (1, 0.5, 2)

x = Variable(torch.Tensor([1]), requires_grad = True) #переменная является обучаемой
z = Variable(torch.Tensor([0.5]), requires_grad = True) #переменная является обучаемой
t = Variable(torch.Tensor([2]), requires_grad = True) #переменная является обучаемой

y = x**3 + z - 75*t
print('Значение функции y в точке:', y.item())

y.backward() #считаем производную по всем переменным

print('Производная функции y по x в точке: ', x.grad.item())
print('Производная функции y по z в точке: ', z.grad.item())
print('Производная функции y по t в точке: ', t.grad.item()) #частные производные

Значение функции y в точке: -148.5
Производная функции y по x в точке:  3.0
Производная функции y по z в точке:  1.0
Производная функции y по t в точке:  -75.0


In [258]:
# №7. Создайте единичный тензор размера 5x6
e = torch.ones([5, 6])
e, e.shape

(tensor([[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]),
 torch.Size([5, 6]))

In [259]:
# №8. Переведите его в формат numpy
e = e.numpy()
e

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)